apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: floorball
  namespace: argocd
spec:
  project: floorball
  source:
    repoURL: "https://github.com/luheine/kubernetes.git"
    targetRevision: main
    path: clusters/minikube/charts/floorball
  destination:
    server: https://kubernetes.default.svc
    namespace: floorball
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
