apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/{{ github_user }}/{{ github_project }}.git"
    targetRevision: main
    path: clusters/minikube/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  project: floorball
  source:
    repoURL: "https://github.com/luheine/floorball.git"
    targetRevision: main
    path: clusters/minikube/apps
    directory:
      recurse: true
  destination:
    server: https://floorball.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
