controller:
  ingressClass: nginx
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  metrics:
    enabled: true
  watchIngressWithoutClass: true
defaultBackend:
  enabled: true
