apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stirlingpdf
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - stirlingpdf.minikube.local
      secretName: stirlingpdf-tls
  rules:
    - host: stirlingpdf.minikube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stirlingpdf
                port:
                  number: 8080
