apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf
  labels:
    app: stirlingpdf
    app.kubernetes.io/instance: stirlingpdf
spec:
  storageClassName: nfs-archive
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi