---
- name: "Add ingress-nginx helm repo"
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: "Install/Upgrade ingress-nginx"
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: "{{ ingress_nginx_namespace }}"
    create_namespace: true
    values_files:
      - "{{ role_path }}/templates/values.yaml.j2"
    wait: true
