image:
  repository: ghcr.io/bastienwirtz/homer
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  enabled: true
  hosts:
    - floorball.lamp.local
  tls:
    - hosts:
        - floorball.lamp.local
      secretName: floorball-tls

