apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: floorball
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - floorball.minikube.local
      secretName: floorball-tls
  rules:
    - host: floorball.minikube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: floorball
                port:
                  number: 8080
