apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sportweb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/luheine/kubernetes.git
    targetRevision: HEAD
    path: clusters/minikube/apps/sportweb
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sportweb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
