apiVersion: apps/v1
kind: Deployment
metadata:
  name: floorball
spec:
  replicas: 1
  selector:
    matchLabels:
      app: floorball
  template:
    metadata:
      labels:
        app: floorball
    spec:
      containers:
        - name: floorball
          image: host.docker.internal/floorball:latest
          ports:
            - containerPort: 80
