apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: floorball-ingress
  namespace: floorball
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: floorball.lamp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: floorball
            port:
              number: 80
